name: final final
options:
  bundleIdPrefix: com.kerim
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    majorVersion: 7.0.0

targets:
  final final:
    type: application
    platform: macOS
    sources:
      - path: final final
        excludes:
          - "**/.DS_Store"
          - "Resources/Export"
          - "Resources/editor"
          - "Resources/TinyTeX"
      - path: final final/Resources/Export
        type: folder
        buildPhase: resources
      - path: final final/Resources/editor
        type: folder
        buildPhase: resources
      - path: final final/Resources/TinyTeX
        type: folder
        buildPhase: resources
      - path: final final/Resources/getting-started.md
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kerim.final-final
        PRODUCT_NAME: FINAL|FINAL
        MARKETING_VERSION: "1"
        CURRENT_PROJECT_VERSION: "0.2.32"
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_ENTITLEMENTS: final final/final final.entitlements
    dependencies:
      - package: GRDB
    info:
      path: final final/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: FINAL|FINAL
        CFBundleName: FINAL|FINAL
        LSMinimumSystemVersion: "14.0"
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true
        CFBundleURLTypes:
          - CFBundleURLName: com.kerim.final-final
            CFBundleURLSchemes:
              - finalfinal
        CFBundleDocumentTypes:
          - CFBundleTypeName: FINAL|FINAL Document
            CFBundleTypeRole: Editor
            LSHandlerRank: Owner
            LSItemContentTypes:
              - com.kerim.final-final.document
        UTExportedTypeDeclarations:
          - UTTypeIdentifier: com.kerim.final-final.document
            UTTypeDescription: FINAL|FINAL Document
            UTTypeConformsTo:
              - com.apple.package
              - public.composite-content
            UTTypeTagSpecification:
              public.filename-extension:
                - ff
          - UTTypeIdentifier: com.kerim.final-final.section
            UTTypeDescription: Section Transfer
            UTTypeConformsTo:
              - public.data
            UTTypeTagSpecification:
              public.mime-type:
                - application/x-final-final-section

  final finalTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: final finalTests
    dependencies:
      - target: final final
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kerim.final-final-tests
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
