#!/bin/bash
#
# ensure-xcodeproj.sh — make sure a sane, generated scheme exists.
#
# The shared scheme (final final.xcodeproj/xcshareddata/xcschemes/final
# final.xcscheme) is generated by xcodegen and untracked in git (see
# .gitignore) — Xcode rewrites it into its own equivalent form on every
# load, which is normal and harmless (see docs/guides/running-tests.md).
# But a fresh clone, a fresh `git worktree add`, or a `git merge` that
# removes this untracked path leaves NO scheme at all until `xcodegen
# generate` runs. This is the cheap, unconditional check every build entry
# point can call: it regenerates only when needed.
#
# Also deletes any Xcode-autocreated USER scheme
# (*.xcodeproj/xcuserdata/*/xcschemes/final final.xcscheme) — if Xcode (GUI
# or the headless Xcode Service agent) opens the project while no shared
# scheme exists, it silently creates its own default user scheme (Test on
# Debug, no DebugTest bundle identity, no FF_E2E_SHOT_DIR forwarding). That
# scheme is gitignored but survives regeneration and would shadow the real
# shared scheme in `xcodebuild -scheme` and Xcode's own scheme picker.
#
# Requires the sandbox disabled when it actually needs to run `xcodegen
# generate` (the same requirement as every other xcodegen call site in this
# repo).
#
# Usage: bash scripts/ensure-xcodeproj.sh
# Exit 0 — a sane scheme is present (regenerated if it wasn't).
# Exit 1 — xcodegen generate failed, or the scheme is still missing/
#          incomplete afterward. Message on stderr.

set -uo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"

SCHEME="final final.xcodeproj/xcshareddata/xcschemes/final final.xcscheme"

# Xcode-autocreated user schemes shadow the real one — remove unconditionally,
# on every call, regardless of whether regeneration below is needed.
find "final final.xcodeproj/xcuserdata" -path "*/xcschemes/final final.xcscheme" -delete 2>/dev/null || true

scheme_is_sane() {
  [ -f "$SCHEME" ] && grep -q "DebugTest" "$SCHEME"
}

if scheme_is_sane; then
  exit 0
fi

echo "ensure-xcodeproj: scheme missing or incomplete — running xcodegen generate (run with the sandbox disabled)." >&2
if ! xcodegen generate; then
  echo "ensure-xcodeproj: xcodegen generate failed. Run 'xcodegen generate' yourself with the sandbox disabled, then retry." >&2
  exit 1
fi

if scheme_is_sane; then
  exit 0
fi

echo "ensure-xcodeproj: scheme still missing or incomplete after xcodegen generate — inspect project.yml's schemes: block." >&2
exit 1
